apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: notejam
build:
  artifacts:
  - image: elhindi/notejam
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - deployment.yml
