name: Java CI with Maven
on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  compile:
    name: Run compilation
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: spring
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Compile code
      run: mvn compile

  # test:
  #   name: Run tests
  #   runs-on: ubuntu-latest
  #   needs: compile
  #   defaults:
  #     run:
  #       working-directory: spring
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Set up JDK 1.8
  #       uses: actions/setup-java@v1
  #       with:
  #         java-version: 1.8

  #     - name: Run unit tests
  #       run: mvn test
  
  build:
    runs-on: ubuntu-latest
    needs: compile
    defaults:
      run:
        working-directory: spring
    steps:
      - name: Checkout
        uses: actions/checkout@master

      # - name: Build/push Docker image
      #   uses: mr-smithers-excellent/docker-build-push@v5
      #   with:
      #     image: elhindi/notejam
      #     tags: v0.4, latest
      #     registry: docker.io
      #     dockerfile: ./spring/Dockerfile
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Lint
        uses: luke142367/Docker-Lint-Action@v0.1.0

      - name: Build/Push Docker image
        uses: opspresso/action-docker@master
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_NAME: "elhindi/notejam"
          TAG_NAME: "v0.4"
          LATEST: "true"
