name: Java CI with Maven
on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:
  compile:
    name: Run compilation
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: spring
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Compile code
      run: mvn compile

  build:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - uses: actions/checkout@master

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build/push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./spring
          file: Dockerfile
          push: true
          tags: elhindi/notejam:0.4
          tag_with_ref: true
