name: Java CI with Maven
on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  compile:
    name: Run compilation
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: spring
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Compile code
      run: mvn compile

  # test:
  #   name: Run tests
  #   runs-on: ubuntu-latest
  #   needs: compile
  #   defaults:
  #     run:
  #       working-directory: spring
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Set up JDK 1.8
  #       uses: actions/setup-java@v1
  #       with:
  #         java-version: 1.8

  #     - name: Run unit tests
  #       run: mvn test
  
  build:
    runs-on: ubuntu-latest
    needs: test
    defaults:
      run:
        working-directory: spring
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Docker Lint
        uses: luke142367/Docker-Lint-Action@v1.0.0
        with:
          target: Dockerfile

      - name: Build/push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: elhindi/notejam
          tags: v0.4, latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
